Change some details of the quick_start guide, which mainly includes t…
MegEngine/Documentation pull request #239
Opened 2021-08-12 06:54 UTC by AsakusaRinne

…he way to define the members of LeNet class. Since the ReLU and MaxPool2D do not have parameters and would not be updated during the training phase, it seems more suitable to initialize single instance of them. Besides, some comments are added.

2021-08-12 06:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/Documentation?pullRequest=239) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/Documentation?pullRequest=239) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/Documentation?pullRequest=239) it.</sub>

2021-08-12 07:27 UTC, MegChai commented
请签署 CLA 协议，稍后进行 review.

2021-08-12 08:05 UTC, MegChai commented
@yzchen @dc3671 PTAL :)

2021-08-12 10:29 UTC, yzchen submitted a review, later dismissed
LGTM。

2021-08-13 05:49 UTC, MegChai requested changes

2021-08-16 06:28 UTC, AsakusaRinne commented on source/getting-started/quick-start.ipynb
> +    "from tqdm import trange\n",
我最初的想法是第一次跑往往是用CPU在本地跑的，新手一般不会直接上服务器和CUDA，这样的话运行起来还是比较慢的，看不到任何变化会心里有点慌，所以当时就想加个进度条。
但用tqdm确实引入了不必要的元素进来，这个并不是训练的必要条件。或许还是用range，然后代码上标注一句只用cpu训练会比较慢比较好一些？

2021-08-16 06:31 UTC, MegChai commented on source/getting-started/quick-start.ipynb
> +    "from tqdm import trange\n",
嗯嗯，跑代码前可以告知用户大概要多久会有输出，这样用户能有一个心理准备。

2021-08-16 06:53 UTC, AsakusaRinne commented on source/getting-started/quick-start.ipynb
> +    "from tqdm import trange\n",
好的，我回去用自己笔记本分别在有GPU加速和没有GPU加速的情况下跑一遍测一下时间，MAC上没有独显。顺便问一下，MegEngine有类似的Benchmark吗？用以说明运行速度和GPU加速情况的

2021-08-16 06:59 UTC, MegChai commented on source/getting-started/quick-start.ipynb
> +    "from tqdm import trange\n",
Benchmark 计划提供中... 这个问题可以单独开一个 Issue.

2021-08-19 01:43 UTC, MegChai commented
gently pin @AsakusaRinne

2021-08-23 04:17 UTC, MegChai requested changes
内容 LGTM. 请按照要求整理 Commit 记录：

1. 使用 git rebase 命令代替 merge 基于 main 分支变基；
2. 要求将所有 Commit 整理为一个单独的 commit 历史；
3. Commit message 符合格式：https://megengine.org.cn/doc/stable/zh/development/contribute-to-docs/commit-message.html

2021-09-08 10:52 UTC, merged