docs(tensor): add format documents (#262)
MegEngine/Documentation pull request #263
Opened 2021-09-10 10:58 UTC by Beichen-Wang

添加了format文档。

2021-09-10 10:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/Documentation?pullRequest=263) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/Documentation?pullRequest=263) before we can accept your contribution.<br/><hr/>**Wang Beichen** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/Documentation?pullRequest=263) it.</sub>

2021-09-10 11:15 UTC, Beichen-Wang commented
@MegChai

2021-09-10 11:24 UTC, Beichen-Wang commented
@MegChai  please review the changes.

2021-09-13 06:35 UTC, MegChai commented
几点建议：

- 考虑到 format 和 layout 关系，建议将 format 的内容挪动到 user-guide/model-development/tensor/layout 中，作为 layout 的一部分进行讲解；
- images 中的图片路径不需要为单独的页面创建子文件夹 ``format``, 这正是为了方便处理上述这种需要修改调整组织的情况，以及你的图片可能也会被其它的文档页面引用，所以建议替换成 ``_static/images/format-xxxx`` 的写法。

题外话：

另外关于 stride 部分的讲解其实并没有写完，当前内容其实是使用了 NumPy 文档中对 Strides 进行通用描述所使用的公式，你可以读一读，给出自己的一些修改建议（注意这块的文档是给用户读的，不要假设他们有框架开发经验）。我们理应让用户有选择去知道执行 reshape, transpose 的时候背后的一些逻辑，但由于过于细节化了，因此目前打算把后续内容放到开发者指南 - MegEngine 幕后揭秘部分。

2021-09-13 06:36 UTC, MegChai requested changes
请参考最新的 Review 意见进行修改。= =!

2021-09-14 12:06 UTC, MegChai commented
你提交 commit 时使用的是一个非 GitHub 账户，建议单独为 Documentation 库进行 git config , username 和 gmail 对应你的 GitHub 账户信息，并且签署 3 楼 Bot 的 CLA.

2021-09-14 12:14 UTC, Beichen-Wang commented
> 几点建议：
> 
> * 考虑到 format 和 layout 关系，建议将 format 的内容挪动到 user-guide/model-development/tensor/layout 中，作为 layout 的一部分进行讲解；
> * images 中的图片路径不需要为单独的页面创建子文件夹 `format`, 这正是为了方便处理上述这种需要修改调整组织的情况，以及你的图片可能也会被其它的文档页面引用，所以建议替换成 `_static/images/format-xxxx` 的写法。
> 
> 题外话：
> 
> 另外关于 stride 部分的讲解其实并没有写完，当前内容其实是使用了 NumPy 文档中对 Strides 进行通用描述所使用的公式，你可以读一读，给出自己的一些修改建议（注意这块的文档是给用户读的，不要假设他们有框架开发经验）。我们理应让用户有选择去知道执行 reshape, transpose 的时候背后的一些逻辑，但由于过于细节化了，因此目前打算把后续内容放到开发者指南 - MegEngine 幕后揭秘部分。

已修改，关于stride的内容，有一个小建议：感觉应该是默认format为NCHW时的步幅，应该在文中描述清楚。

2021-09-14 12:14 UTC, Beichen-Wang commented
> 你提交 commit 时使用的是一个非 GitHub 账户，建议单独为 Documentation 库进行 git config , username 和 gmail 对应你的 GitHub 账户信息，并且签署 3 楼 Bot 的 CLA.

好的。

2021-09-15 03:56 UTC, MegChai commented
还是有些不规范，需要再处理一下：

1. 提交了两个 commit, 应当合并为一个，并去掉非 GitHub 账户的 Author;
2. 仍然在 images 目录下创建了 format 文件夹，看起来只是复制了 svg 图片，而不是移动 & 重命名。

2021-09-15 20:16 UTC, MegChai approved these changes
LGTM

2021-09-15 20:16 UTC, merged

2021-09-22 09:53 UTC, MegChai commented
你在提交 PR 的时候是不是遇到了 Git LFS 问题呀（push 不上来）？我看这个 PR 最终提交上来的四个图片是二进制文件，这样会让别人 rebase 或者 pull 的时候出现 LFS 相关的警告，现在已经改成文件指针了。