docs(source/user-guide): add custom op user guide
MegEngine/Documentation pull request #269
Opened 2021-09-14 09:25 UTC by cqchu

add custom op user guide documentation

@MegChai please kindly review

2021-09-14 09:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/Documentation?pullRequest=269) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/Documentation?pullRequest=269) before we can accept your contribution.<br/><hr/>**test** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/Documentation?pullRequest=269) it.</sub>

2021-09-14 09:29 UTC, MegChai commented
签署 CLA 协议要保证 commit 中的 author 都是真实的 GitHub 账户，调整一下 git config 信息，然后签署 CLA 吧

2021-09-14 09:36 UTC, lixiangyin666 commented
如果能有一个预览版，就对reviewer很友好了，不然还要脑补一下生成后的格式

2021-09-14 09:38 UTC, MegChai commented
> 如果能有一个预览版，就对reviewer很友好了，不然还要脑补一下生成后的格式

目前提供两种做法，方便其他人进行预览：

1. 点开上面的 Gitpod.io  用云 IDE 环境预览（服务部署在国外）；
2. 等 CI 跑成功后，点开 CI 的 pipeline ，会有个 artifacts 文件可以下载，解压后预览。

2021-09-14 09:48 UTC, lixiangyin666 reviewed
> > 如果能有一个预览版，就对reviewer很友好了，不然还要脑补一下生成后的格式
> 
> 目前提供两种做法，方便其他人进行预览：
> 
> 1. 点开上面的 Gitpod.io  用云 IDE 环境预览（服务部署在国外，慢）；
> 2. 等 CI 跑成功后，点开 CI 的 pipeline ，会有个 artifacts 文件可以下载，解压后预览。

强，发现不用下载就可以预览了

2021-09-14 09:48 UTC, lixiangyin666 commented on source/user-guide/tools/customop.rst
> +一般而言，研究人员可以使用 MegEngine 提供的 python 接口去拓展 Function 和 Module 去实现的其所需的功能。
> 研究人员可以使用 MegEngine 提供的 python 接口去拓展 Function 和 Module 去实现的其所需的功能。

->
研究人员可以使用 MegEngine 提供的 python 接口**通过**拓展 Function 和 Module 去实现其所需的功能。

2021-09-14 09:51 UTC, MegChai commented on source/user-guide/tools/customop.rst
> +一般而言，研究人员可以使用 MegEngine 提供的 python 接口去拓展 Function 和 Module 去实现的其所需的功能。
可以考虑在评论的时候使用 Insert a suggestion （一个带 +- 符号的图标），这样方便 assignee 接受并整理 commit

2021-09-14 11:10 UTC, xxr3376 commented
文档 LGTM，不过对于这种复杂的例子，我们是不是提供一个 custom op 样例仓库会更方便大家快速上手呢？（大家可以直接对着这个仓库直接改…）

2021-09-14 11:13 UTC, MegChai commented
> 文档 LGTM，不过对于这种复杂的例子，我们是不是提供一个 custom op 样例仓库会更方便大家快速上手呢？（大家可以直接对着这个仓库直接改…）

我建议在 Documentation 的 examples 里面加文件夹，比如 ``examples/customop``, 理由是方便阅读也方便维护、流量集中。或者搞个单独的 Examples 库，不过非常容易被误认为是 Model Example.

2021-09-14 11:14 UTC, xxr3376 submitted a review, later dismissed

2021-09-14 11:16 UTC, xxr3376 commented
@MegChai 我个人 prefer 独立 repo，原因是这样毕竟简洁清楚，别人想基于这个改也只需要 fork 一份就行，不过感觉完全可以独立于这份文档。

2021-09-14 12:24 UTC, cqchu commented
> @cqchu 现在这份文档的内容 LGTM. 写得很好。
> 
> 吹毛求疵，提一些细节问题：
> 
> * code-block:: 语法后面可以跟参数，默认是 python，建议 c++ 代码用 `code-block:: cpp` 指定语言
> * 如果你的句子是用英文字母或者代码结尾，最后一个符号用英文句号 `.` 而不是中文句号`。`
> * 对于一些不同属性的介绍，除了用 ** 加粗来区分外，我更推荐使用 2 格缩进的 [定义列表](https://megengine.org.cn/doc/stable/zh/development/contribute-to-docs/restructuredtext.html#id3)

好的，我改一下

2021-09-15 02:01 UTC, lixiangyin666 requested changes

2021-09-15 02:13 UTC, cqchu commented on source/user-guide/tools/customop.rst
> +        .set_compute("cuda", compute);      // 设置这个 Op 的 计算函数
暂时还没有API文档，我先记个JIRA吧

2021-09-15 03:00 UTC, MegChai commented on source/user-guide/tools/customop.rst
> +        .set_compute("cuda", compute);      // 设置这个 Op 的 计算函数
在 0.6 版本的时候我们确实有尝试用 Doxyfile + Breath 的形式 gen 一个 C++ API 出来，可以看这块：

https://megengine.org.cn/api/0.6/cpp_api/library_root.html

但是你实际体验一下会发现，这就和当时的 Python API 一样，虽然大而全，但是内容空洞，对用户的帮助甚微。

在研究出具体可行的 C++ API 方案之前（至少这个 Q 不会做这个事情），我们截图先专注于写 **好** 用户指南和提供 example, 能解决教用户如何用的燃眉之急。如果为了达到某个目的简单地引入整个 MegEngine C++ domain 的 API 会让后续的维护变复杂。 @xxr3376 至少现在以我对哪些 C++ 接口要暴露的了解程度，还无法胜任这样的活，如果急着要的话，要找个更加有经验的人来思考如何做好这件事情。

2021-09-15 03:09 UTC, MegChai commented
@cqchu 点一下 https://github.com/MegEngine/Documentation/pull/269#issuecomment-918976959 的 CLA 签署吧～

2021-09-15 03:12 UTC, cqchu commented on source/user-guide/tools/customop.rst
> +一般而言，研究人员可以使用 MegEngine 提供的 python 接口去拓展 Function 和 Module 去实现的其所需的功能。
已经改好了

2021-09-15 03:14 UTC, cqchu commented
> @cqchu 点一下 [#269 (comment)](https://github.com/MegEngine/Documentation/pull/269#issuecomment-918976959) 的 CLA 签署吧～

OK，已经签好了！！

2021-09-15 03:15 UTC, cqchu commented on source/user-guide/tools/customop.rst
> +   class MatMulScale(Function):        # 将我们定义的 Op 包装成 Function
更新成了Custom op在python中如何使用以及如何基于Custom op去封装成 Function 和 Module

2021-09-15 03:18 UTC, cqchu commented
> * code-block:: 语法后面可以跟参数，默认是 python，建议 c++ 代码用 `code-block:: cpp` 指定语言
> * 如果你的句子是用英文字母或者代码结尾，最后一个符号用英文句号 `.` 而不是中文句号`。`
> * 对于一些不同属性的介绍，除了用 ** 加粗来区分外，我更推荐使用 2 格缩进的 [定义列表](https://megengine.org.cn/doc/stable/zh/development/contribute-to-docs/restructuredtext.html#id3)

前两点已经改好了，最后一点我发现使用之后文档的内容好像也会有缩进，感觉不是预期的效果所以我就没改了

2021-09-15 03:23 UTC, lixiangyin666 approved these changes

2021-09-15 03:26 UTC, MegChai approved these changes
Others, LGTM.

@cqchu 后面和 @xxr3376 交流一下到底是在 Documentation 加 Example 还是独立弄一个 Customop example 的 repo 会比较好维护，我个人倾向是全部弄到 Documentation （包括量化、AMP、Lite 等等），如果区分开的话也行，但意味着必须保证相关文档所 refer 的 repo 得有人维护，如果没人维护的话我拒绝将这样的 reference 引入到官方文档中（比如 xor-sdk）。

2021-09-15 04:01 UTC, cqchu commented on source/user-guide/tools/customop.rst
> +        .set_compute("cuda", compute);      // 设置这个 Op 的 计算函数
行，那等 Chai 把 C++ API方案定下来之后再来看决定这个文档该怎么写，在此之前先通过给 API 头文件注释的方式去指导用户的使用

2021-09-15 05:17 UTC, merged

2021-09-15 06:51 UTC, xxr3376 commented on source/user-guide/tools/customop.rst
> +        .set_compute("cuda", compute);      // 设置这个 Op 的 计算函数
同意，C++ API 文档很不好整，我们先用良好的 example 和用户指南来解决这个问题