Add lite docs
MegEngine/Documentation pull request #308
Opened 2021-11-23 07:34 UTC by chenqy4933

2021-11-23 07:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/Documentation?pullRequest=308) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/Documentation?pullRequest=308) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/Documentation?pullRequest=308) it.</sub>

2021-11-23 07:38 UTC, chenqy4933 commented
@MegChai review 一下~

2021-11-23 09:19 UTC, MegChai commented
正在 review, 可能需要花一些时间。

以下是目前疑惑的一些地方：

- MegEngine 文档用户指南中的 《推理部署篇》 可以认为是 Lite 文档的主阵地，之前旧版本的 C++ 部署文章（XOR 为例这篇）虽然理应被删除，但是 deployment/index.rst 这个文件不应该被直接删除，这会导致收藏了 https://megengine.org.cn/doc/stable/zh/user-guide/deployment/index.html 地址的用户以后打开时 404. 我期望的是 Lite 文档能作为整个推理指南的主入口，因此建议：用一些对推理部署概念的基本介绍 “替换” 掉 deployment/index.rst 中的旧有内容，然后提到我们推荐的方法是使用 MegEngine Lite.
- @chenqy4933  从你的角度来看， 《TraceModule 发版方案》是不是应该归纳到模型开发阶段中？当时这个文档是直接在内部文档写的，没有太多考究就急着同步过来了。

关于 Lite 的 Python /  C++ 使用接口：

- Python 接口可以依旧使用 Sphinx 来生成，放在  API Reference 页面
- 如果 C++ 接口不打算走 Doxygen 和 breath 的形式来自动生成，我们也可以手动在 API Reference 中手写每个接口，工作量和维护成本与现在的手写形式相当。

我可能会造一个 PR 来体现这个事情。

2021-11-23 09:26 UTC, chenqy4933 commented
> 

第一点非常好，我后面修改一下。《TraceModule 发版方案》方案我觉得可以放在模型开发阶段，但是放在推理阶段似乎也说得过去。

python和C++生成的接口文档可能没有这么易懂，因为现在在code层面就没有写多少注释，所以生成的文档应该基本上不能看，但是维护性更好一些。目前手写了，后面有人在lite中添加或者修改接口的话，都建议他来更新这个的文档。

2021-11-29 06:02 UTC, MegChai commented
gently pin @chenqy4933  这个 MR 是属于 WIP 状态，还是希望先把这部分的文档合入？

2021-11-29 06:04 UTC, MegChai requested changes
一些格式上的问题需要完善，内容方面第一版没什么要求，根据用户反馈调整。

关于 Lite API 这件事情，可以按照现在的已有内容出来，后面花时间人工完善。

2021-11-29 08:43 UTC, chenqy4933 commented
> gently pin @chenqy4933 这个 MR 是属于 WIP 状态，还是希望先把这部分的文档合入？

先merge吧，后面再提pr

2021-11-29 08:43 UTC, chenqy4933 commented on source/user-guide/deployment/lite/fast-develope-cpp.rst
> + * 创建默认配置的 Network
done

2021-11-29 08:44 UTC, chenqy4933 commented on source/user-guide/deployment/lite/index.rst
> +   fast-develope-python
done

2021-11-29 08:44 UTC, chenqy4933 commented on source/user-guide/deployment/lite/index.rst
> +   fast-develope-cpp
done

2021-11-29 11:01 UTC, merged