docs(traced_module): update traced_module
MegEngine/Documentation pull request #318
Opened 2021-12-07 03:06 UTC by CaoWGG

更新了一下 TracedModule 的文档，
把 `deployment/traced_module/index` 放在了 `模型开发（进阶篇）` ，但未更换文件地址

2021-12-07 04:10 UTC, MegChai commented
正在 Review, 临时预览页面：https://megchai-megengine-documentation-wggpx9v939r56-1124.githubpreview.dev/user-guide/deployment/traced_module/index.html

2021-12-07 04:34 UTC, MegChai requested changes
整体来说内容上更加地面向用户了，很不错的改进，样式细节上需要做一些修改。

对于 API 接口的介绍是必须的，最初更新时没有时间去完善 API Docstring 所以选择了放在用户指南中的某个页面介绍，但始终感觉它只是一个中间状态的产物，最终它的归处应当是 API Reference. 如果现在耐心地在用户指南中补充各个 API 的定义和 Example，反而会形成将来的技术债，得今早考虑 API Reference 页面的建设了。

2021-12-07 04:34 UTC, MegChai commented on source/user-guide/deployment/traced_module/graphsurgeon-example.rst
>      :class: dropdown
关于 :class: dropdown 这个下拉样式，有没有用户反馈说过这样看起来很麻烦？我理解这是为了节省屏幕空间，让用户只关注自己想看的部分，但是现在用户可以通过右侧的导航栏跳转了，要求下拉是不是有些多余了呢？

![image](https://user-images.githubusercontent.com/21091736/144964949-7f886d00-df02-425c-885c-dc0f5915c5ac.png)

如果一个人想顺序看完，每个都要点一下，挺麻烦的。如果可以找实际用户获取真实反馈，建议主动问问，

2021-12-07 04:34 UTC, MegChai commented on source/user-guide/deployment/traced_module/index.rst
> +   :maxdepth: 3
如果是为了展示详尽的组织结构，感觉可以统一都设置 `maxdepth` 为 3，然后放在一个 toctree 下

2021-12-07 04:34 UTC, MegChai commented on source/user-guide/index.rst
> +   deployment/traced_module/index
由于文档是按照模型开发 -> 部署流程顺序组织的，从这个原则上看，jit (dump) 永远是 模型开发最底下的一个章节，用来衔接部署文档，因此建议 traced_module 上挪。

以及这样放置虽然兼容了历史 URL 访问，但看起来很怪。如果我们确定了 traced_module 一开始放在部署里面的做法是不符合用户期望的，现在应该容许及时的修正，不能吊死在兼容性一棵树上。

 @xxr3376 求信息：文档的 404 & 定向跳转搞了不？给 traced_module 加个 deployment/traced_module -> model-development/traced_module 规则？

2021-12-07 04:34 UTC, MegChai commented on source/user-guide/deployment/traced_module/graphsurgeon-example.rst
> +=======================
WARNING: Title overline too short.

把这两道线加长些...

2021-12-07 04:34 UTC, MegChai commented on source/user-guide/deployment/traced_module/api-example.rst
> +    **示例：**
这个列表中的代码示例部分都多缩进了一个，会导致多一个奇怪的引用样式：

![image](https://user-images.githubusercontent.com/21091736/144966670-fe99915a-c234-4d43-a996-db763a71fb47.png)

2021-12-07 04:34 UTC, MegChai commented on source/user-guide/deployment/traced_module/api-example.rst
> +**示例1：** 向 layer1 中的所有 ``F.relu`` 后插入一个 ``F.neg`` 函数
ditto

2021-12-07 04:34 UTC, MegChai commented on source/user-guide/deployment/traced_module/api-example.rst
> +    * 当一个 conv module 被调用多次时，我们将会对其拷贝，并设置一个新的 name，以使其转变为被调用一次，如下面的例子
ditto

![image](https://user-images.githubusercontent.com/21091736/144966792-8d8a0fad-e11a-4705-87e2-5ebb0a43f872.png)

2021-12-07 04:34 UTC, MegChai commented on source/user-guide/deployment/traced_module/api-example.rst
> +* 不支持全局变量（Tensor），即跨 Module 使用 ``Tensor`` 将会得到不可预知的结果，如下面的例子：
ditto

![image](https://user-images.githubusercontent.com/21091736/144966825-e1aa7beb-4b02-4723-8a77-3ca8acf16e84.png)

2021-12-07 04:39 UTC, MegChai commented
有一个之前提到过的问题没被解决：

traced_module 的文档和 Lite 的性质还是有些不一样的，后者没有 API Reference, 所以写在了用户指南里面来达到情景全覆盖。但对于教用户如何使用某个 feature 的文档来说，我们不能寄希望让用户指南解决 API Reference 的问题，反而要尽可能避免罗列定义。我能想到的比较理想的做法是在 Traced Module 自己的 API Reference 中给出说明和使用的 Example. 

我能想到的麻烦的地方：

- 要在 Python 源码中写一大堆的英文文档字符串
- 还需要在新版本的时候做翻译

尽管我们总是可以通过列举 API 的形式来达到类似的效果，但这样反而会导致我们把最初的要求不断地 delay 掉，毕竟已经有了个替代方案的话，就更加没有人愿意去完善 Docstring 这样的东西了。

2021-12-07 05:26 UTC, xxr3376 commented on source/user-guide/deployment/traced_module/graphsurgeon-example.rst
>      :class: dropdown
做为一个经常看这个页面的人，我绝大多数需要浏览的时候只关心文本部分，代码只会在我需要特定功能的时候才会看，我觉得折叠着挺好的

2021-12-07 05:27 UTC, xxr3376 commented on source/user-guide/index.rst
> +   deployment/traced_module/index
@MegChai 定向跳转从来也没决定要做，需要文档和官网整套机制 codesign 才行

2021-12-11 08:05 UTC, CaoWGG commented on source/user-guide/deployment/traced_module/index.rst
> +   :maxdepth: 3
done

2021-12-11 08:06 UTC, CaoWGG commented on source/user-guide/deployment/traced_module/graphsurgeon-example.rst
> +=======================
done

2021-12-11 08:08 UTC, CaoWGG commented on source/user-guide/deployment/traced_module/api-example.rst
> +    **示例：**
done

2021-12-11 08:34 UTC, CaoWGG commented on source/user-guide/deployment/traced_module/graphsurgeon-example.rst
>      :class: dropdown
目前更新后的 TM 文档中，用到下拉样式的地方都有大段的代码（且并不是必须展示的内容），快占满整个屏幕了，感觉很不友好，就给折叠起来了。

对于几行的例子代码都已改成 ``>>>`` 这种方式展示。

另外我个人感觉右边导航栏存在感很低，左边的导航栏存在感很强烈。

2021-12-11 08:57 UTC, CaoWGG commented on source/user-guide/index.rst
> +   deployment/traced_module/index
已移到 ``jit`` 之前。
 
TracedModule 目前是位于 模型（训练） 到 最终部署（推理）的一个中间产物，它更接近训练（未来预期也要参与训练，例如 QAT），确实应该放在 ``模型开发（进阶）`` 中。

2021-12-11 10:52 UTC, MegChai submitted a review, later dismissed
Others, LGTM.   还需要找一个 Reviewer 看看内容，目前需要确保在下周五之前这个 PR 能合入。

其它信息：

- 内容需要下拉这件事情，我想可能是目前的样式有些尬，所以影响了我的判断，它本身是一件合理的事情；
- Example 代码怎么放这件事，随着 tm 和 lite 文档的引入，变成了一个需要考虑的事情。我目前有一个计划是：为了降低文档里面 code 维护的难度，使用 ``.. literalinclude:: filename`` 这样的语法来从 ``Documentation/example/xxxx/xxx.py`` 里面引用，好处是显而易见的，可以加 CI 跑测试，以及一处改动多处引用即时生效。目前 ``example`` 这个文件夹的作用并没有发挥出来，只是一些 model 结构的集合。

至于 API Reference 这部分，当时 1.6 发版的时候，只是口头要求了后面一定要改进，可以用一个版本的时间继续优化，但没说要怎么改怎么做，下周我们约个时间把相关的改进方案和执行步骤敲定下来吧，我也想听听你的思路，顺带也可以聊聊量化文档这边打算怎么进一步添加内容。

2021-12-11 10:54 UTC, MegChai commented
gently ping @xxr3376 @lixiangyin666

2021-12-11 12:54 UTC, CaoWGG commented
@MegChai 把 `  .. admonition:: :class: dropdown` 换成了 `.. dropdown::`，感觉好一些
![image](https://user-images.githubusercontent.com/41051066/145676791-0bdd2736-5b5a-49d2-aa06-febd98526f3a.png)

OK。 量化文档，原计划是随着 TM 量化相关的 feature 一起整理并提交，但最近忙于其他事情，量化相关的排期往后延了延。

2021-12-13 05:08 UTC, CaoWGG commented
@dingshaohua960303 求 review 一波

2021-12-13 10:18 UTC, MegChai submitted a review, later dismissed
LGTM.

2021-12-14 03:00 UTC, dingshaohua960303 commented
局限可以加下调用functional时建议使用 F.xxx 而不是 from functional import xxx，后一种写法可能无法被trace到而被识别成opdef调用。 others LGTM

2021-12-14 05:38 UTC, CaoWGG commented
> 局限可以加下调用functional时建议使用 F.xxx 而不是 from functional import xxx，后一种写法可能无法被trace到而被识别成opdef调用。 others LGTM

done

2021-12-14 05:52 UTC, lixiangyin666 commented
LGTM

2021-12-14 05:58 UTC, lixiangyin666 commented
从traced module dump出C++序列化文件是不是要提一下

2021-12-14 06:09 UTC, CaoWGG commented on source/user-guide/model-development/traced_module/api-example.rst
> +    * ``name``  新增输入的名字，默认为 "args"，若该名字在 Graph 种已存在，则会在 name 后添加后缀，以保证 name 在 Graph 在的唯一性。
done

2021-12-14 06:16 UTC, CaoWGG commented
> 从traced module dump出C++序列化文件是不是要提一下，然后是不是在dump后的部署也关联一下lite的链接

在 [快速上手 TracedModule/ TracedModule 模型部署](https://github.com/MegEngine/Documentation/pull/318/files#diff-f4a535dcb9f17fb0f2425b545fa59ec44cd9f02d2e856e62d2a5a375ab6928f9R89-R98) 添加了模型部署相关引用。

2021-12-14 07:30 UTC, lixiangyin666 approved these changes

2021-12-14 07:41 UTC, merged