docs(environ): add fastrun cache env vars
MegEngine/Documentation pull request #343
Opened 2021-12-30 12:55 UTC by GetUpEarlier

添加fastrun cache配置相关的两个环境变量，以便用户在默认cache配置不可用时更改配置

2021-12-30 12:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/Documentation?pullRequest=343) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/Documentation?pullRequest=343) before we can accept your contribution.<br/><hr/>**chenjinsong** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/Documentation?pullRequest=343) it.</sub>

2021-12-30 12:58 UTC, MegChai requested changes

2021-12-30 12:58 UTC, MegChai commented on source/reference/environment-variables.rst
> +  使用何种方式存储fastrun cache，可设置为 ``FILE``，``MEMORY``
```suggestion
  使用何种方式存储 fastrun cache, 可设置为 ``FILE`` 或 ``MEMORY``
```
另外最好详细解释一下两个设置之间的区别。

2021-12-30 12:58 UTC, MegChai commented on source/reference/environment-variables.rst
> +  更改fastrun cache的存储存储路径，默认为 ``~/.cache/megengine/persistent_cache``
```suggestion
  更改 fastrun cache 的存储路径，默认为 ``~/.cache/megengine/persistent_cache``
```

2022-01-04 06:22 UTC, MegChai commented
gently pin @GetUpEarlier

2022-01-06 09:13 UTC, GetUpEarlier commented on source/reference/environment-variables.rst
> +  使用何种方式存储fastrun cache，可设置为 ``FILE``，``MEMORY``
Done.

2022-01-06 09:14 UTC, GetUpEarlier commented on source/reference/environment-variables.rst
> +  更改fastrun cache的存储存储路径，默认为 ``~/.cache/megengine/persistent_cache``
Done.

2022-01-07 09:04 UTC, MegChai approved these changes

2022-01-07 09:04 UTC, merged