feat(user_guide):add load and run doc
MegEngine/Documentation pull request #400
Opened 2022-04-06 06:05 UTC by yeasoon

2022-04-06 06:08 UTC, yeasoon commented
@MegChai @chenqy4933 please help to review

2022-04-06 06:14 UTC, MegChai commented
Build 过程中引入了 26 个 warnings, 需要 fix 

https://deprecated.readthedocs.io/en/latest/sphinx_deco.html

2022-04-06 07:34 UTC, yeasoon commented
@MegChai  done

2022-04-06 08:38 UTC, MegChai requested changes
commit 信息中文档内容的修改统一视作 docs 类型，此 PR 中应当为：

```
docs(guide): add load and run doc
```

格式方面除了上面提到的一些小细节，其他地方都很棒。还没来得及通读整个文档内容，会在后面给出进一步的 Review.

2022-04-06 09:39 UTC, yeasoon commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +* 确定出现问题的 ``设备平台`` ，明确推理时用到的应后端，使用时才能参考 load and run device 相关的选项进行设置。
done

2022-04-06 09:39 UTC, yeasoon commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +    .. code:: python
done

2022-04-06 09:39 UTC, yeasoon commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +
done

2022-04-06 11:35 UTC, MegChai commented
内容比较多，预计周五前给出内容方面的 Review.

2022-04-07 04:19 UTC, MegChai commented
本楼用于讨论关于 ”推理模型获取“ 的介绍部分放置位置，范围不局限于 LAR 文档本身。

- 背景：在 MegEngine 中的模型文件存在 `.pkl` 与 `.mge` 两类的区分，后者专指通过 `dump` 序列化得到的文件。在 C++ 的推理情境中，必须使用 `.mge` 模型文件。因此获取模型文件往往成了推理流程中的第一步（被介绍到的）操作。
- 现状：目前关于 `.mge` 文件的获取操作放在了 Lite 层级内， 路径为 `user-guide/deployment/lite/get-model.html`
- 问题：Load and run 同样需要用到 `.mge`  文件，《模型以及相关支持》页面中这部分的介绍跳转指向了 Lite 中相关页面，
- 建议：将获取模型的介绍放置在《[模型部署总览与流程建议](https://www.megengine.org.cn/doc/stable/zh/user-guide/deployment/index.html)》 中作为流程中必需的一小节进行介绍（最终指向 `dump` 用户指南以供参考），不再作为单独的页面。

需要强调 `dump` 这一步完成之后，训练情景与推理情景的衔接关系。

需要获得三位的一致同意 @yeasoon @chenqy4933 @xxr3376 ，将另外开 PR 进行挪动尝试。

2022-04-07 05:17 UTC, MegChai requested changes

2022-04-07 05:17 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/basic_usage.rst
> +MegEngine 1.7 之后，load and run 集成了对 MegEngine lite 接口的支持，可以使用 load and run 对 MegEngine lite 相关的模型进行推理测试,
这个 PR 有比较多的关于 MegEngine 1.7 版本的信息强调，可以考虑使用 Sphinx 专有的 Directives 以获得视觉样式:

```restrutctext
.. versionadded:: 1.7

   集成了对 MegEngine Lite 接口的支持，可对 Lite 相关的模型进行推理测试。
```

可省略主语，效果形如《[Tensor 数据类型](https://www.megengine.org.cn/doc/stable/zh/user-guide/model-development/tensor/dtype.html)》 页面中对 uint16 支持版本的介绍：

![image](https://user-images.githubusercontent.com/21091736/162124701-7679c84e-2913-4ae4-9ac4-04c22a9c0a3b.png)

Refs:

- https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionchanged
- https://github.com/MegEngine/Documentation/blame/main/source/user-guide/model-development/tensor/dtype.rst#L109

2022-04-07 05:17 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/build-lar.rst
> +   load and run 是 MegEngine 配套的 C++ 推理工具，v1.7 以前是位于 MegEngine 工程 ``sdk/load-and-run`` 目录下面的，v1.7 之后支持 MegEngine lite 相关的推理接口，迁移到了 ``lite/load_and_run`` 目录下。所以如果需要获取 ``load and run`` 的源码，可以拉取 `Megengi
Ditto.

2022-04-07 05:17 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/model-support.rst
> +   load and run 通常情况下使用 Megengine 的相关接口进行模型推理，v1.7 之后提供了对 MegEngine lite 接口的支持。
Ditto. 关于这个页面以及  `ref:get-model` 是否要独立存在的讨论见：

https://github.com/MegEngine/Documentation/pull/400#issuecomment-1091063803

2022-04-07 05:18 UTC, MegChai commented
之前的文档 build CI 有缺陷不会挂在 warning 情况下，需要 rebase 一下最新的 main 分支。

2022-04-07 05:32 UTC, MegChai requested changes
PR 中英文排版规范做得很出色，还是有漏网之鱼：

1. load and run 如果作为 MegEngine 中的专用名词，不论出现在正文中何处，首字母应当是大写的；缩写形式应当统一为 LAR, 而非 lar.
2. 中英文之间需要有空格，有几个地方疏忽了
3. 如果是英文单词作为结尾，句末使用英文标点符号，如 —— Load and run.  而非 Load and run。或 Load and run 。

2022-04-07 05:32 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +.. _accuracy_debug:
```suggestion
.. _load-and-run-accracy-analysis:
```

建议改动原因如下：

- 为了方面在其它页面中进行 ref, label name 带上关于 namespace 的信息会比较好，比如 xxx-guide, xxx-tutorial, lite-xxxx 等等
- 这里的标题既然用了分析，对应的英文 label 准确点可以用 analysis

默认给文档加上全局可用的 reference label 是非常好的习惯，点赞

2022-04-07 05:32 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/index.rst
> +.. toctree::
这里的文件命名风格非常不统一，MegEngine 文档中 rst 文件名会直接影响到最终渲染出的 HTML 页面的 URL, 建议使用统一的风格，目前绝大多数 file name 都是使用 `-` 作为分隔符，而不使用 `_`.

2022-04-07 05:32 UTC, MegChai commented on source/user-guide/tools/load-and-run.rst
> +C++ load and run 有很多丰富的配置选项，可以通过 ``--help`` 查看具体功能，更多细节请参考 :ref:`megengine_load_and_run`
感觉除非是为了防止 URL 死链的负面影响， Load and run 相关页面放在 《工具与插件篇》的意义已经不大了，可以完全移动到《推理部署篇》。对于 LAR Python 接口的介绍也可以一并地移过去。cc  @xxr3376

2022-04-07 05:32 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/index.rst
> +使用 MegEngine load and run (C++) 进行模型推理
标题这里不用再强调 C++ 了，按照目前的内容量比例，可以发现 Python 接口的介绍作为一个 LAR 目录下的子页面，并在 index 页面中简单 ref 一下就行了。

2022-04-07 05:44 UTC, MegChai requested changes
还有类似的 Ditto 项目没有标出，建议统一做出如下修改：

- load and run -> Load and run
- load and run 。 -> Load and run. （英文词结尾的标点符号用半角的 , 和  . ）
- lite -> Lite

2022-04-07 05:44 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +出现上述的精度抖动时，首先需要确认问题出现的环境并对问题进行精简，建立一个可以使用load and run 运行的最小复现环境。
```suggestion
出现上述的精度抖动时，首先需要确认问题出现的环境并对问题进行精简，建立一个可以使用 Load and run 运行的最小复现环境。
```

2022-04-07 05:44 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +* 确认出现问题的 **MegEngine 版本** ，选择对应版本编译相应的 load and run 。
```suggestion
* 确认出现问题的 **MegEngine 版本** ，选择对应版本编译相应的 Load and run.
```

2022-04-07 05:44 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +在以上基本的信息的基础上编译获取相应平台可用的 load and run 程序，确定需要设置的配置接口之后就可以使用load and run 进行问题复现了
```suggestion
在以上基本的信息的基础上编译获取相应平台可用的 Load and run 程序，确定需要设置的配置接口之后就可以使用 Load and run 进行问题复现了
```

2022-04-07 05:44 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +使用 load and run 进行精度分析
```suggestion
使用 Load and run 进行精度分析
```

2022-04-07 05:44 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +当这种情况发生时，可以使用 load and run 进行问题定位，分析产生这一问题的原因。
```suggestion
当这种情况发生时，可以使用 Load and run 进行问题定位，分析产生这一问题的原因。
```

2022-04-07 05:44 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +下面就使用 load and run 进行精度分析的使用方法进行介绍。
```suggestion
下面就使用 Load and run 进行精度分析的使用方法进行介绍。
```

2022-04-07 05:44 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +* 确定出现问题的 **设备平台** ，明确推理时用到的应后端，使用时才能参考 load and run device 相关的选项进行设置。
```suggestion
* 确定出现问题的 **设备平台** ，明确推理时用到的应后端，使用时才能参考 Load and run 中 ``device`` 相关的选项进行设置。
```

2022-04-07 05:44 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +.. code:: python
![image](https://user-images.githubusercontent.com/21091736/162127886-9d6b2661-94e3-492a-bca9-7dbeef9538f7.png)

这块 code 是作为 List element 元素出现的，需要缩进 3 格与其所对应的元素保持一致。

2022-04-07 05:44 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +   * load and run 的一些设置选项需要在编译时配置相应的宏才可以开启，编译时需要注意，可以参考各个设置选项的说明。
```suggestion
   * Load and run 的一些设置选项需要在编译时配置相应的宏才可以开启，编译时需要注意，可以参考各个设置选项的说明。
```

2022-04-07 05:44 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +问题复现后需要对出现问题的原因进行进一步排查，主要目的时定位精度出现问题的 layer 以及 opr. 下面就一些常见的场景进行介绍。
layer 和 opr 这种英文术语在中文文档中需要翻译成中文，它们不是和 LAR 一样的专有名词。

2022-04-07 05:44 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +在添加新的算子实现时，因为部分情况未覆盖等原因，导致有些模型推理过程中出现计算错误。这时需要确定出错 opr 所在位置。
```suggestion
在添加新的算子实现时，因为部分情况未覆盖等原因，导致有些模型推理过程中出现计算错误。这时需要确定出错的算子所在位置。
```

2022-04-07 05:44 UTC, MegChai commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +MegEngine 模型的计算图在运行时是以计算序列的形式逐步执行的，使用load and run 的 输入输出 dump 相关设置选项就可以得到计算序列中各个计算节点对应的输入输出。
```suggestion
MegEngine 模型的计算图在运行时是以计算序列的形式逐步执行的，使用 Load and run 的 输入输出 dump 相关设置选项就可以得到计算序列中各个计算节点对应的输入输出。
```

2022-04-07 07:06 UTC, yeasoon commented on source/user-guide/deployment/lite/load_and_run/basic_usage.rst
> +MegEngine 1.7 之后，load and run 集成了对 MegEngine lite 接口的支持，可以使用 load and run 对 MegEngine lite 相关的模型进行推理测试,
done

2022-04-07 07:06 UTC, yeasoon commented on source/user-guide/deployment/lite/load_and_run/build-lar.rst
> +   load and run 是 MegEngine 配套的 C++ 推理工具，v1.7 以前是位于 MegEngine 工程 ``sdk/load-and-run`` 目录下面的，v1.7 之后支持 MegEngine lite 相关的推理接口，迁移到了 ``lite/load_and_run`` 目录下。所以如果需要获取 ``load and run`` 的源码，可以拉取 `Megengi
done

2022-04-07 07:06 UTC, yeasoon commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +.. _accuracy_debug:
done

2022-04-07 07:07 UTC, yeasoon commented on source/user-guide/tools/load-and-run.rst
> +C++ load and run 有很多丰富的配置选项，可以通过 ``--help`` 查看具体功能，更多细节请参考 :ref:`megengine_load_and_run`
done

2022-04-07 07:07 UTC, yeasoon commented on source/user-guide/deployment/lite/load_and_run/index.rst
> +使用 MegEngine load and run (C++) 进行模型推理
done

2022-04-07 07:07 UTC, yeasoon commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +出现上述的精度抖动时，首先需要确认问题出现的环境并对问题进行精简，建立一个可以使用load and run 运行的最小复现环境。
done

2022-04-07 07:07 UTC, yeasoon commented on source/user-guide/deployment/lite/load_and_run/accuracy_debug.rst
> +问题复现后需要对出现问题的原因进行进一步排查，主要目的时定位精度出现问题的 layer 以及 opr. 下面就一些常见的场景进行介绍。
done

2022-04-11 04:10 UTC, MegChai approved these changes
LATM. 因为最近的一篇 PR 文章提到了 Load and run, 这个 PR 先合入了，一些样式上的修改会提交一个 fix PR 进行，内容上的修改等待用户反馈。

2022-04-11 04:10 UTC, merged