misc: add api coverage test script
MegEngine/Documentation pull request #458
Opened 2022-07-12 12:06 UTC by MegChai

2022-07-13 02:27 UTC, xxr3376 requested changes

2022-07-13 02:28 UTC, xxr3376 commented on scripts/api-coverage.py
> +def check_module(top_module):
先看这个问题吧，感觉大结构上可以先把问题简化一下

2022-07-13 05:23 UTC, MegChai commented on scripts/api-coverage.py
> +
Done.

2022-07-13 05:23 UTC, MegChai commented on scripts/api-coverage.py
> +            if not function_name.startswith("_"):
Done.

2022-07-13 05:23 UTC, MegChai commented on scripts/api-coverage.py
> +lost_api_list = []
Done.

2022-07-13 05:23 UTC, MegChai commented on scripts/api-coverage.py
> +visit_module = []
Done.Done.Done.Done.

2022-07-13 05:24 UTC, MegChai commented on scripts/api-coverage.py
> +        if module.__name__.startswith("megengine.core"):
一个是只针对 single module （不带任何前后缀 . ）一个是带前缀的黑名单的情况，写法上应该可以优化

2022-07-13 05:24 UTC, MegChai commented on scripts/api-coverage.py
> +        if not module.__name__.startswith("megengine"):
Done.

2022-07-13 05:25 UTC, MegChai commented on scripts/api-coverage.py
> +for (dirpath, dirnames, filenames) in os.walk(generated_api_path):
一开始是奔着快速糙能跑通的代码去写的，交了很糙的一版本，所以是想到啥写啥。。

2022-07-13 05:25 UTC, MegChai commented on scripts/api-coverage.py
> +def check_module(top_module):
Done. 感觉目前的实现还是有些耦合，我再想想。

2022-07-13 06:48 UTC, xxr3376 commented on scripts/api-coverage.py
> +    visit_module = set()  # temporary memory for DFS
`visited_module`

2022-07-13 06:58 UTC, xxr3376 requested changes

2022-07-13 06:58 UTC, xxr3376 commented on scripts/api-coverage.py
> +                        if obj_id not in api_alias.keys():
`keys()`没必要

2022-07-13 06:58 UTC, xxr3376 commented on scripts/api-coverage.py
> +        target_api: Set[API] = (),
Nit: 感觉 target_api 是个没必要耦合在这里面的东西，直接让这个函数返回 `api_alias` 就行（相当于只负责抽取所有的 `memref -> set(name)`），区分哪些是已经生成过的在另外的函数里再遍历一次就好了

2022-07-13 06:58 UTC, xxr3376 commented on scripts/api-coverage.py
> +        target_api: Set[API] = (),
这样的话，main 里就三个步骤，也比较清晰了

1. get_generated_api
2. get_all_api
3. diff

2022-07-13 07:40 UTC, MegChai commented on scripts/api-coverage.py
> +        target_api: Set[API] = (),
想了一下，确实可以做，但是如果为了解耦合，从而多遍历一次的开销感觉很麻烦额 o_o . 目前的实现其实等于对 ``get_all_api`` 的基础实现进行了一次拓展，能够快速地在给定  ``target_api`` 的时候拿到对应的 ``id`` 组成的集合。且在默认情况下  ``target_api``  是个空集合，用户调这个接口如果只是想取所有的 api 信息，可以不给 ``target_api`` 参数，同时也不取返回值中的 ``target_api_id``, 当它不存在。

By the way, 发现 ``all_api_id`` 和 ``all_api_alias`` 维护的信息是冗余的，现在统一合并成  ``api_info`` 了。

2022-07-13 07:40 UTC, MegChai commented on scripts/api-coverage.py
> +                        if obj_id not in api_alias.keys():
Done

2022-07-13 07:40 UTC, MegChai commented on scripts/api-coverage.py
> +    visit_module = set()  # temporary memory for DFS
Done.

2022-07-14 03:01 UTC, xxr3376 requested changes

2022-07-14 03:01 UTC, xxr3376 commented on scripts/api-coverage.py
> +        return api_info, target_api_id
这样的 function return desgin 太可怕了，不要搞这种不同情况下返回不同结果的函数

2022-07-14 07:56 UTC, xxr3376 approved these changes

2022-07-14 08:49 UTC, GetUpEarlier submitted a review, later dismissed

2022-07-14 09:36 UTC, MegChai commented
从当前结果来看还有一些情况需要被剪枝如 ``megengine.traced_module.traced_module.isclass``, 正在完善

2022-07-14 10:47 UTC, merged